# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'awsuploadreactnative' do
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
end

target 'awsuploadreactnative-tvOS' do
  system("mkdir -p Pods/Headers/Public/FirebaseCore && cp Pods/FirebaseCore/Firebase/Core/Public/* Pods/Headers/Public/FirebaseCore/")
end